name: "prototype"
domains:
    intergers:
      name: "integers_executor"
      path: "domains.math.integers_domain"
    circle:
      name: "circle_executor"
      path: "domains.spatial.circle_domain"

vocab:
    path: "data/core_vocab.txt"
