name: "prototype"
domains:
    intergers:
      name: "integer_executor"
      path: "domains.math.integer_domain"
    euclid:
      name: "euclid_executor"
      path: "domains.math.euclid_domain"
    color:
      name: "color_executor"
      path: "domains.visual.color_domain"
    logic:
      name: "fol_executor"
      path: "domains.logic.fol_domain"

vocab:
    path: "data/core_vocab.txt"
