name: "prototype"
domains:
    intergers:
      name: "integer_executor"
      path: "domains.math.integer_domain"
    objects:
      name: "objects_executor"
      path: "domains.scene.objects_domain"
    logic:
      name: "fol_executor"
      path: "domains.logic.fol_domain"

vocab:
    path: "data/core_vocab.txt"
